// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamTask.Data.Contexts;

#nullable disable

namespace TeamTask.Data.Migrations
{
    [DbContext(typeof(TeamTaskDBContext))]
    [Migration("20240401100421_userNoteTbl")]
    partial class userNoteTbl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "449d244c-5a63-4ca4-b19f-0c9a0cdef696",
                            RoleId = "ee2b7220-4f94-4237-a019-f53e67619be5"
                        },
                        new
                        {
                            UserId = "449d244c-5a63-4ca4-b19f-0c9a0cdef696",
                            RoleId = "58fd95fc-2c1f-420d-967e-cadc3b498475"
                        },
                        new
                        {
                            UserId = "28c3df3a-1ed1-4fdb-841b-836fc9eba5f4",
                            RoleId = "58fd95fc-2c1f-420d-967e-cadc3b498475"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ee2b7220-4f94-4237-a019-f53e67619be5",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "58fd95fc-2c1f-420d-967e-cadc3b498475",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "449d244c-5a63-4ca4-b19f-0c9a0cdef696",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "620eed8d-798f-49f5-89ae-346904014e50",
                            Email = "muratoz@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Murat",
                            LastName = "Öz",
                            LockoutEnabled = false,
                            NormalizedEmail = "MURATOZ@GMAIL.COM",
                            NormalizedUserName = "MURATOZ",
                            PasswordHash = "AQAAAAIAAYagAAAAEOXXQ53mg0egXu7WYwpta5n5daJRPqjxTjh5fwZsl7tnH1JMy7e9xZ9flFx0hHbobQ==",
                            PhoneNumber = "5555555555",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b8d21030-2052-4cc1-af2f-7301bc960502",
                            TwoFactorEnabled = false,
                            UserName = "muratoz"
                        },
                        new
                        {
                            Id = "28c3df3a-1ed1-4fdb-841b-836fc9eba5f4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "526dfc69-e892-470f-9f40-1c3c4b19910b",
                            Email = "engin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Engin",
                            LastName = "Niyazi",
                            LockoutEnabled = false,
                            NormalizedEmail = "ENGIN@GMAIL.COM",
                            NormalizedUserName = "ENGIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEIXrfZOquYwTwcGs5aVyp6AZ7+Gjrq/ZEzvwYrRtgiPgpbmbC9n5cpJaicza4n+gEQ==",
                            PhoneNumber = "5555555554",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c8fe5fc5-1475-4e00-8cbc-f99dfd392a6f",
                            TwoFactorEnabled = false,
                            UserName = "engin"
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "gray",
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1547),
                            DisplayText = "Başlanmadı",
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1547)
                        },
                        new
                        {
                            Id = 2,
                            Color = "yellow",
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1548),
                            DisplayText = "Sürüyor",
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1549)
                        },
                        new
                        {
                            Id = 3,
                            Color = "green",
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1550),
                            DisplayText = "Bitti",
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1550)
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1560),
                            EndDate = new DateTime(2024, 4, 2, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1561),
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1560),
                            Priority = 0,
                            Title = "Task 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1565),
                            EndDate = new DateTime(2024, 4, 3, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1566),
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1566),
                            Priority = 2,
                            Title = "Task 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1567),
                            EndDate = new DateTime(2024, 4, 4, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1568),
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1567),
                            Priority = 1,
                            Title = "Task 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1568),
                            EndDate = new DateTime(2024, 4, 2, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1569),
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1569),
                            Priority = 0,
                            Title = "Task 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1570),
                            EndDate = new DateTime(2024, 4, 3, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1570),
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1570),
                            Priority = 1,
                            Title = "Task 5"
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.TaskStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StatusId", "TaskId");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.ToTable("TaskStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            TaskId = 1
                        },
                        new
                        {
                            StatusId = 2,
                            TaskId = 2
                        },
                        new
                        {
                            StatusId = 1,
                            TaskId = 3
                        },
                        new
                        {
                            StatusId = 3,
                            TaskId = 4
                        },
                        new
                        {
                            StatusId = 3,
                            TaskId = 5
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.TaskUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskUsers");

                    b.HasData(
                        new
                        {
                            UserId = "449d244c-5a63-4ca4-b19f-0c9a0cdef696",
                            TaskId = 1
                        },
                        new
                        {
                            UserId = "28c3df3a-1ed1-4fdb-841b-836fc9eba5f4",
                            TaskId = 2
                        },
                        new
                        {
                            UserId = "449d244c-5a63-4ca4-b19f-0c9a0cdef696",
                            TaskId = 3
                        },
                        new
                        {
                            UserId = "28c3df3a-1ed1-4fdb-841b-836fc9eba5f4",
                            TaskId = 4
                        },
                        new
                        {
                            UserId = "449d244c-5a63-4ca4-b19f-0c9a0cdef696",
                            TaskId = 5
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.UserNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserNote");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Bu benim test notumdur!",
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1337),
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1351),
                            NoteTitle = "Bunu unutma",
                            Priority = 2,
                            UserId = "449d244c-5a63-4ca4-b19f-0c9a0cdef696"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Bu benim test notumdur2!",
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1356),
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1357),
                            NoteTitle = "Bunu unutma 2",
                            Priority = 1,
                            UserId = "28c3df3a-1ed1-4fdb-841b-836fc9eba5f4"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Bu benim test notumdur3!",
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1358),
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1358),
                            NoteTitle = "Bunu unutma 3",
                            Priority = 0,
                            UserId = "449d244c-5a63-4ca4-b19f-0c9a0cdef696"
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.WorkingSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkingSpaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#ff0000",
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1400),
                            Description = "Benim çalışma alanım 1 harika bir çalışma alanı!",
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1401),
                            Title = "Benim çalışma alanım 1",
                            UserId = "449d244c-5a63-4ca4-b19f-0c9a0cdef696"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#00ff00",
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1403),
                            Description = "Benim çalışma alanım 2 harika bir çalışma alanı!",
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1404),
                            Title = "Benim çalışma alanım 2",
                            UserId = "449d244c-5a63-4ca4-b19f-0c9a0cdef696"
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.WorkingSpaceComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkingSpaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkingSpaceId");

                    b.ToTable("WorkingSpaceComments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Harika bir çalışma alanı",
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1517),
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1518),
                            UserId = "449d244c-5a63-4ca4-b19f-0c9a0cdef696",
                            WorkingSpaceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Güzel bir çalışma olacak",
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1521),
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1522),
                            UserId = "28c3df3a-1ed1-4fdb-841b-836fc9eba5f4",
                            WorkingSpaceId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Tekrar yorum yaptım",
                            CreatedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1523),
                            ModifiedDate = new DateTime(2024, 4, 1, 13, 4, 21, 257, DateTimeKind.Local).AddTicks(1524),
                            UserId = "449d244c-5a63-4ca4-b19f-0c9a0cdef696",
                            WorkingSpaceId = 1
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.WorkingSpaceTask", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkingSpaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId", "WorkingSpaceId");

                    b.HasIndex("WorkingSpaceId");

                    b.ToTable("WorkingSpaceTasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            WorkingSpaceId = 1
                        },
                        new
                        {
                            TaskId = 2,
                            WorkingSpaceId = 2
                        },
                        new
                        {
                            TaskId = 3,
                            WorkingSpaceId = 1
                        },
                        new
                        {
                            TaskId = 4,
                            WorkingSpaceId = 2
                        },
                        new
                        {
                            TaskId = 5,
                            WorkingSpaceId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamTask.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.TaskStatus", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamTask.Entity.Concrete.Task", "Task")
                        .WithOne("TaskStatus")
                        .HasForeignKey("TeamTask.Entity.Concrete.TaskStatus", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.TaskUser", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Task", "Task")
                        .WithMany("TaskUsers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamTask.Entity.Concrete.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.UserNote", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Identity.User", null)
                        .WithMany("NoteList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.WorkingSpaceComment", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamTask.Entity.Concrete.WorkingSpace", null)
                        .WithMany("Comments")
                        .HasForeignKey("WorkingSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.WorkingSpaceTask", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Task", "Task")
                        .WithMany("WorkingSpaceTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamTask.Entity.Concrete.WorkingSpace", "WorkingSpace")
                        .WithMany("WorkingSpaceTasks")
                        .HasForeignKey("WorkingSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("WorkingSpace");
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.Identity.User", b =>
                {
                    b.Navigation("NoteList");
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.Task", b =>
                {
                    b.Navigation("TaskStatus")
                        .IsRequired();

                    b.Navigation("TaskUsers");

                    b.Navigation("WorkingSpaceTasks");
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.WorkingSpace", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("WorkingSpaceTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
