// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamTask.Data.Contexts;

#nullable disable

namespace TeamTask.Data.Migrations
{
    [DbContext(typeof(TeamTaskDBContext))]
    [Migration("20240321162210_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "4bc5058e-474a-44ea-b133-5ca250dae639",
                            RoleId = "d8dc52fa-b159-4ff9-a68a-eac4cc48cae7"
                        },
                        new
                        {
                            UserId = "4bc5058e-474a-44ea-b133-5ca250dae639",
                            RoleId = "88a46cb9-0683-40cf-9e7c-cabac843470d"
                        },
                        new
                        {
                            UserId = "bfc24732-ffe5-4caa-a8d5-79c074b7c0c0",
                            RoleId = "88a46cb9-0683-40cf-9e7c-cabac843470d"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d8dc52fa-b159-4ff9-a68a-eac4cc48cae7",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "88a46cb9-0683-40cf-9e7c-cabac843470d",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4bc5058e-474a-44ea-b133-5ca250dae639",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b46caee0-b537-4bd8-9982-fee2f81d51dc",
                            Email = "muratoz@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Murat",
                            LastName = "Öz",
                            LockoutEnabled = false,
                            NormalizedEmail = "MURATOZ@GMAIL.COM",
                            NormalizedUserName = "MURATOZ",
                            PasswordHash = "AQAAAAIAAYagAAAAEAkMAe4tRknKqDSV8yDKXcaDoa45bs7PywpRgMbxnnhZfJIxh41K9wnd77UG5I/rOQ==",
                            PhoneNumber = "5555555555",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e7cd4dbd-3211-4af3-bf05-6e723949d5ae",
                            TwoFactorEnabled = false,
                            UserName = "muratoz"
                        },
                        new
                        {
                            Id = "bfc24732-ffe5-4caa-a8d5-79c074b7c0c0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "222110ba-ce5e-447e-a421-e3996a32162d",
                            Email = "engin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Engin",
                            LastName = "Niyazi",
                            LockoutEnabled = false,
                            NormalizedEmail = "ENGIN@GMAIL.COM",
                            NormalizedUserName = "ENGIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEEFrjzdhoJ7mQ5N1fU0Ok3xy+Ldpq/cf9RYyNPtC7QQhEl9s0+cB6SZpKhMnBvASdg==",
                            PhoneNumber = "5555555554",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3fbaeb68-aabe-48f4-8ae7-09ccb7476cdb",
                            TwoFactorEnabled = false,
                            UserName = "engin"
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "gray",
                            CreatedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(491),
                            DisplayText = "Başlanmadı",
                            ModifiedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(491)
                        },
                        new
                        {
                            Id = 2,
                            Color = "yellow",
                            CreatedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(492),
                            DisplayText = "Sürüyor",
                            ModifiedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(492)
                        },
                        new
                        {
                            Id = 3,
                            Color = "green",
                            CreatedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(493),
                            DisplayText = "Bitti",
                            ModifiedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(493)
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(503),
                            EndDate = new DateTime(2024, 3, 22, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(504),
                            ModifiedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(503),
                            Priority = 0,
                            Title = "Task 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(509),
                            EndDate = new DateTime(2024, 3, 23, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(510),
                            ModifiedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(510),
                            Priority = 0,
                            Title = "Task 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(511),
                            EndDate = new DateTime(2024, 3, 24, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(512),
                            ModifiedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(511),
                            Priority = 0,
                            Title = "Task 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(512),
                            EndDate = new DateTime(2024, 3, 22, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(513),
                            ModifiedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(513),
                            Priority = 0,
                            Title = "Task 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(514),
                            EndDate = new DateTime(2024, 3, 23, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(514),
                            ModifiedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(514),
                            Priority = 0,
                            Title = "Task 5"
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.TaskStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StatusId", "TaskId");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.ToTable("TaskStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            TaskId = 1
                        },
                        new
                        {
                            StatusId = 2,
                            TaskId = 2
                        },
                        new
                        {
                            StatusId = 1,
                            TaskId = 3
                        },
                        new
                        {
                            StatusId = 3,
                            TaskId = 4
                        },
                        new
                        {
                            StatusId = 3,
                            TaskId = 5
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.TaskUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskUsers");

                    b.HasData(
                        new
                        {
                            UserId = "4bc5058e-474a-44ea-b133-5ca250dae639",
                            TaskId = 1
                        },
                        new
                        {
                            UserId = "bfc24732-ffe5-4caa-a8d5-79c074b7c0c0",
                            TaskId = 2
                        },
                        new
                        {
                            UserId = "4bc5058e-474a-44ea-b133-5ca250dae639",
                            TaskId = 3
                        },
                        new
                        {
                            UserId = "bfc24732-ffe5-4caa-a8d5-79c074b7c0c0",
                            TaskId = 4
                        },
                        new
                        {
                            UserId = "4bc5058e-474a-44ea-b133-5ca250dae639",
                            TaskId = 5
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.WorkingSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkingSpaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#ff0000",
                            CreatedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(341),
                            ModifiedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(350),
                            Title = "My space",
                            UserId = "4bc5058e-474a-44ea-b133-5ca250dae639"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#00ff00",
                            CreatedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(355),
                            ModifiedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(355),
                            Title = "My space 2",
                            UserId = "4bc5058e-474a-44ea-b133-5ca250dae639"
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.WorkingSpaceComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkingSpaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkingSpaceId");

                    b.ToTable("WorkingSpaceComments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Harika bir çalışma alanı",
                            CreatedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(454),
                            ModifiedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(454),
                            UserId = "4bc5058e-474a-44ea-b133-5ca250dae639",
                            WorkingSpaceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Güzel bir çalışma olacak",
                            CreatedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(459),
                            ModifiedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(459),
                            UserId = "bfc24732-ffe5-4caa-a8d5-79c074b7c0c0",
                            WorkingSpaceId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Tekrar yorum yaptım",
                            CreatedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(462),
                            ModifiedDate = new DateTime(2024, 3, 21, 19, 22, 10, 847, DateTimeKind.Local).AddTicks(463),
                            UserId = "4bc5058e-474a-44ea-b133-5ca250dae639",
                            WorkingSpaceId = 1
                        });
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.WorkingSpaceTask", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkingSpaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId", "WorkingSpaceId");

                    b.HasIndex("WorkingSpaceId");

                    b.ToTable("WorkingSpaceTasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            WorkingSpaceId = 1
                        },
                        new
                        {
                            TaskId = 2,
                            WorkingSpaceId = 2
                        },
                        new
                        {
                            TaskId = 3,
                            WorkingSpaceId = 1
                        },
                        new
                        {
                            TaskId = 4,
                            WorkingSpaceId = 2
                        },
                        new
                        {
                            TaskId = 5,
                            WorkingSpaceId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamTask.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.TaskStatus", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamTask.Entity.Concrete.Task", "Task")
                        .WithOne("TaskStatus")
                        .HasForeignKey("TeamTask.Entity.Concrete.TaskStatus", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.TaskUser", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Task", "Task")
                        .WithMany("TaskUsers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamTask.Entity.Concrete.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.WorkingSpaceComment", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamTask.Entity.Concrete.WorkingSpace", null)
                        .WithMany("Comments")
                        .HasForeignKey("WorkingSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.WorkingSpaceTask", b =>
                {
                    b.HasOne("TeamTask.Entity.Concrete.Task", "Task")
                        .WithMany("WorkingSpaceTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamTask.Entity.Concrete.WorkingSpace", "WorkingSpace")
                        .WithMany("WorkingSpaceTasks")
                        .HasForeignKey("WorkingSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("WorkingSpace");
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.Task", b =>
                {
                    b.Navigation("TaskStatus")
                        .IsRequired();

                    b.Navigation("TaskUsers");

                    b.Navigation("WorkingSpaceTasks");
                });

            modelBuilder.Entity("TeamTask.Entity.Concrete.WorkingSpace", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("WorkingSpaceTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
